name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Cambia esto por la rama de despliegue si no usas "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'  # Asegúrate de usar la versión correcta de Node.js para tu proyecto

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Crear build para producción
      - name: Build project
        run: npm run build

      # Paso 5: Desplegar en Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --project ${{ secrets.VERCEL_PROJECT_ID }} --org ${{ secrets.VERCEL_ORG_ID }}
