name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Cambia esta rama si es necesario

jobs:
  deploy:
    name: Deploy to Production
    env:
      VERCEL_TOKEN: pwY5hKK6jBuzft5E4VUpfK4g
      
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 5: Desplegar en Vercel (sin usar Org ID)
      - name: Deploy to Production Vercel
        run: |
          echo "Desplegando aplicacion a producción..."
          npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
