name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Cambia esta rama si es necesario

jobs:
  deploy:
    name: Deploy
    env:
      VERCEL_TOKEN: pwY5hKK6jBuzft5E4VUpfK4g
      VERCEL_PROJECT_ID: prj_AcmPpztlox7kv9yTdbNy8eBS3Saw
      
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Desplegar en Vercel (sin usar Org ID)
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --project ${{ secrets.VERCEL_PROJECT_ID }}
