name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Cambia esta rama si es necesario

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar dotenv-cli para cargar variables del archivo .env.production
      - name: Install dotenv-cli
        run: npm install -g dotenv-cli

      # Paso 3: Cargar variables de .env.production y desplegar en Vercel
      - name: Deploy to Vercel
        run: dotenv -e .env.production npx vercel --prod --token $VERCEL_TOKEN --project $VERCEL_PROJECT_ID
