name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Cambia esta rama si es necesario

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Desplegar en Vercel con valores directamente
      - name: Deploy to Vercel
        run: npx vercel --prod --token pwY5hKK6jBuzft5E4VUpfK4g --project prj_AcmPpztlox7kv9yTdbNy8eBS3Saw
